version: "3"
services:
  bd:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
   volumes:
      - ./sql/create.sql:/docker-entrypoint-initdb.d/1.sql
    restart: always
    networks:
      - lanproxy  
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  php:
    image: php:fpm-alpine	  

  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - lanproxy
	depends_on:
	  - bd

  app1:
    image: nginx
    volumes:
	  - ./conf/default.conf /etc/nginx/conf.d
      - ./php/index.php:/var/www/html/index.php:ro	
    restart: always
    networks:
      - lanproxy
	depends_on:
	  - bd
  
  app2:
    image: nginx
    volumes:
	  - ./dconf/efault.conf /etc/nginx/conf.d
      - ./php/index.php:/var/www/html/index.php:ro	
    restart: always
    networks:
      - lanproxy
	depends_on:
	  - bd

  app3:
    image: nginx
    volumes:
	  - ./conf/default.conf /etc/nginx/conf.d
      - ./php/index.php:/var/www/html/index.php:ro	
    restart: always
    networks:
      - lanproxy
	depends_on:
	  - bd	  
	  
    networks: 
        - lanproxy	  